# 1. Partimos de una imagen ligera de Python 3.11
FROM python:3.11-slim

# 2. Creamos el directorio de trabajo
WORKDIR /app

# 3. Copiamos los ficheros de dependencias y código
COPY requirements.txt app.py sensor_pb2.py sensor_pb2_grpc.py ./

# 4. Instalamos las dependencias sin caché
RUN pip install --no-cache-dir -r requirements.txt

# 5. Comando por defecto al iniciar el contenedor
CMD ["python", "app.py"]